[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'suan/vim-instant-markdown'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'
